[project]
name = "digisim"
version = "0.1.0"
description = "A digital simulation project using SimPy"
authors = [
    
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "simpy>=4.0.1",
    "numpy>=1.23.0",
    "geopandas>=0.10.0",
    "netCDF4>=1.5.0",
    "python-dotenv>=0.19.0",
    "requests>=2.26.0",
    "apscheduler>=3.10",
    "httpx>=0.27",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["models*", "services*", "scheduler*", "utils*"]
exclude = ["config*", "export*", "tests*", "documentation*"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
