[project]
name = "digisim"
version = "0.1.0"
description = "A digital simulation project using SimPy"
authors = [
    
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.1",
    "netcdf4>=1.7.2",
    "numpy>=2.3.2",
    "simpy>=4.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["models*", "services*", "scheduler*", "utils*"]
exclude = ["config*", "export*", "tests*", "documentation*"]
